---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-2"
  tasks: 
    - name: Create RDS subnet group
      rds_subnet_group: 
        name: m5-ig-private-dbgrp
        description: M5 image gallery private db subnet group
        state: present
        subnets: 
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
      register: rds_subnet
    - name: Create RDS instance
      rds:      
        command: create
        instance_name: m5-image-gallery
        db_engine: postgres
        size: 8
        instance_type: db.t2.micro
        username: m5admin
        password: replaceThisPassword
        tags: 
          Module: 5
        subnet: "{{ rds_subnet.subnet_group.name }}"
      
