---
- hosts: localhost
  gather_facts: no
  module_defaults: 
    group/aws:
      region: "us-west-2"
  tasks: 
    - name: Create VPC
      ec2_vpc_net: 
        name: m5-image-gallery-vpc
        cidr_block: 10.0.0.0/16
        tags: 
          Module: 5
          Name: m5-image-gallery-vpc
        state: present
      register: vpc
    - name: debug
      debug: var=vpc
    - name: Create public subnet one
      ec2_vpc_subnet: 
        tags: 
          Name: m5-ig-public-1-sn
          Module: 5
        vpc_id: "{{ vpc.vpc.id  }}"
        cidr: 10.0.5.0/24
        az: us-west-2a
        state: present
      register: public_subnet_1
    - name: Create public subnet two
      ec2_vpc_subnet:
        tags:
          Name: m5-ig-public-2-sn
          Module: 5
        vpc_id: "{{ vpc.vpc.id  }}"
        cidr: 10.0.6.0/24
        az: us-west-2b
        state: present
      register: public_subnet_2
    - name: Create private subnet one
      ec2_vpc_subnet:
        tags:
          Name: m5-ig-private-1-sn
          Module: 5
        vpc_id: "{{ vpc.vpc.id  }}"
        cidr: 10.0.7.0/24
        az: us-west-2a
        state: present
      register: private_subnet_1
    - name: Create private subnet two
      ec2_vpc_subnet:
        tags:
          Name: m5-ig-private-2-sn
          Module: 5
        vpc_id: "{{ vpc.vpc.id  }}"
        cidr: 10.0.8.0/24
        az: us-west-2b
        state: present
      register: private_subnet_2
    - name: Create internet gateway
      ec2_vpc_igw: 
        vpc_id: "{{ vpc.vpc.id  }}"
        tags: 
          Name: m5-igw
        state: present
      register: igw
    - name: Create NAT gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet_1.subnet.id  }}"
        wait: yes
        if_exist_do_not_create: true
        state: present
      register: nat_gateway
    - name: Create public route table
      ec2_vpc_route_table: 
        vpc_id: "{{ vpc.vpc.id }}"
        tags: 
          Name: m5-ig-public-rtb
        subnets: 
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
        routes:
          - dest: 10.0.0.0/16
            gateway_id: local
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
    - name: Create private route table
      ec2_vpc_route_table: 
        vpc_id: "{{ vpc.vpc.id }}"
        tags: 
          Name: m5-ig-private-rtb
        subnets: 
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
        routes:
          - dest: 10.0.0.0/16
            gateway_id: local
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gateway.nat_gateway_id }}"
    - name: Create public network ACL
      ec2_vpc_nacl: 
        vpc_id: "{{ vpc.vpc.id }}"
        name: m5-ig-public-acl
        tags:
          Name: m5-ig-public-acl
        subnets: ['public_subnet_1', 'public_subnet_2']
        ingress: 
          - [100, 'tcp', 'allow', '71.212.211.194/32', null, null, 5000, 5000]
          - [110, 'tcp', 'allow', '24.196.25.139/32', null, null, 5000, 5000]
          - [120, 'tcp', 'allow', '24.239.105.213/32', null, null, 5000, 5000]
          - [130, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]
          - [140, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
          - [150, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80]
        egress: 
          - [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 1024, 65535]
          - [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 80, 80]
          - [120, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443]
        state: 'present'
    - name: Create private network ACL
      ec2_vpc_nacl: 
        vpc_id: "{{ vpc.vpc.id }}"
        name: m5-ig-private-acl
        tags:
          Name: m5-ig-private-acl
        subnets: ['private_subnet_1', 'private_subnet_2']
        ingress: 
          - [100, 'tcp', 'allow', '10.0.0.0/16', null, null, 5432, 5432]
          - [110, 'tcp', 'allow', '10.0.5.0/24', null, null, 22, 22]
          - [120, 'tcp', 'allow', '10.0.0.0/16', null, null, 443, 443]
        egress: 
          - [100, 'tcp', 'allow', '10.0.0.0/16', null, null, 1024, 65535]
          - [110, 'tcp', 'allow', '0.0.0.0/0', null, null, 443, 443]
        state: 'present'
    - name: Create m5-ig-postgres-tag sg
      ec2_group: 
        name: m5-ig-postgres-tag
        description: m5-ig-postgres-tag security group
        vpc_id: "{{ vpc.vpc.id }}"
        state: 'present'
      register: m5_ig_postgres_tag
    - name: Create m5-ig-postgres security group
      ec2_group:
        name: m5-ig-postgres
        description: ig postgres tag security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 8080 
              - 5432
            group_name: 
              - "{{ m5_ig_postgres_tag.group_id }}"
            group_desc: m5 ig postgres tag group
          - proto: tcp
            ports: 
              - 443
            cidr_ip: 0.0.0.0/0
        state: 'present'
      register: m5_ig_postgres 
    - name: Update m5-ig-postgres-tag security group
      ec2_group:
        name: m5-ig-postgres-tag
        description: ig postgres tag security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules_egress:
          - proto: tcp
            ports: 
              - 5432
              - 443
            group_name: 
              - "{{ m5_ig_postgres.group_id }}"
        state: present
    - name: Create m5 ig development security group
      ec2_group:
        name: m5-ig-development
        description: ig development security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 80
              - 5000
            cidr_ip: 
              - 71.212.211.194/32
              - 24.196.25.139/32
              - 24.239.105.213/32
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
        rules_egress: 
          - proto: tcp
            ports: 
              - 80
              - 22
              - 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: 
              - 5000
            cidr_ip: 
              - 71.212.211.194/32
              - 24.196.25.139/32
              - 24.239.105.213/32
        state: present 
      register: m5_ig_development
    - name: Create nginx-servers security group
      ec2_group:
        name: m5-nginx-servers
        description: nginx servers security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 
              - 71.212.211.194/32
              - 24.196.25.139/32
              - 24.239.105.213/32
          - proto: tcp
            ports: 
              - 22
            cidr_ip: 0.0.0.0/0
        state: present      
      register: m5_nginx_servers
    - name: Create m5-secrets-manager-tag sg
      ec2_group:
        name: m5-secrets-manager-tag
        description: m5-secrets-manager-tag security group
        vpc_id: "{{ vpc.vpc.id }}"
        state: 'present'
      register: m5_secrets_manager_tag
    - name: Create m5-secrets-manager security group
      ec2_group:
        name: m5-secrets-manager
        description: m5 secrets manager security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports: 
              - 443
            group_name:
              - "{{ m5_secrets_manager_tag.group_id }}"
            group_desc: m5 secrets manager tag
        state: present
      register: m5_secrets_manager
    - name: Update secrets-manager-tag security group
      ec2_group:
        name: m5-secrets-manager-tag
        description: m5-secrets-manager-tag security group
        vpc_id: "{{ vpc.vpc.id }}"
        rules_egress:
          - proto: tcp
            ports:
              - 443
            group_name:
              - "{{ m5_secrets_manager.group_id }}"
            group_desc: m5 secrets manager group
        state: present
